### ISSUE TITLE
Coffee Script dependency

### ISSUE THREAD

**Issue by cbas** [jviotti/idid#2]
After installation (see #1 ) it seems there is a dependency on globally installed `coffee-script`. Can this be moved to `package.json`'s `dependencies` instead? Currently it's in `devDependencies` which is not available at run time.

A workaround for users right now is:

    nmp install -g coffee-script

**Comment by jviotti** [comment]
Definitely right, fixed in https://github.com/jviotti/idid/pull/3.

**Comment by cbas** [comment]
Thanks :) :+1:
